#
#
#okta:
#  oauth2:
#    clientId:
#    clientSecret:
#    issuer: https://dev-984936.okta.com/oauth2/default
#    audience: http://localhost:8081
#
#
#
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-984936.okta.com/oauth2/default/v1/keys