
#server:
#  port: 8080
#
#
#okta:
#  oauth2:
#    clientId:
#    clientSecret:
#    issuer: https://dev-984936.okta.com/oauth2/default
#    audience: http://localhost:8081

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-984936.okta.com/oauth2/default
        registration:
          okta:
            client-id:
            client-secret:
      resource:
        server: http://localhost:8081